apiVersion: v1
kind: Namespace
metadata:
  name: postgresdb
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgresdb
type: Opaque
data:
  postgres-user: Z2VvcmdpYQ==
  postgres-password: Z2VvcmdpYQ==